version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./ui
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
